on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: push-al1
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: al1/Dockerfile
          repository: nmoutschen/rust-lambda-build-images-al1
          tag_with_ref: true

      - name: push-al2
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: al2/Dockerfile
          repository: nmoutschen/rust-lambda-build-images-al2
          tag_with_ref: true
